sudo: required
services:
  - docker

before_install: 
  - docker build -t don2001l/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true don2001l/docker-react npm run test -- --coverage
